--Aufgabe 2.1
SELECT JOB,ENAME FROM emp WHERE ENAME LIKE '%a%';
-- Aufgabe 2.2
SELECT ENAME,HIREDATE FROM emp WHERE ENAME LIKE '%er';
-- Aufgabe 2.3
SELECT EMPNO, ENAME FROM emp WHERE ENAME LIKE 'A____';